# Vector Norms - Finding the Lp norm of a vector

Vectors are represented as n-dimensional arrays in Python.

And, creating a vector is as simple as following,

In [3]:
import numpy as np

In [4]:
one_dimensional_vector = np.array([1]) 
two_dimensional_vector = np.array([1, 2])
three_dimensional_vector = np.array([1, 2, 3])

print(f"1D Vector: {one_dimensional_vector} | Shape of vector: {one_dimensional_vector.shape}")
print(f"2D Vector: {two_dimensional_vector} | Shape of vector: {two_dimensional_vector.shape}")
print(f"3D Vector: {three_dimensional_vector} | Shape of vector: {three_dimensional_vector.shape}")

1D Vector: [1] | Shape of vector: (1,)
2D Vector: [1 2] | Shape of vector: (2,)
3D Vector: [1 2 3] | Shape of vector: (3,)


To perform simple vector operations such as addition, subtraction, multiplication or divisions, vectors need to have the same shape. Using two vectors `a` and `b` to demonstrate multiple vector operations,

In [5]:
a = np.array([1, 2])
b = np.array([3, 4])

In [6]:
# Addition -> Performs element wise addition [1+3 2+4] = [4, 6]
a + b

array([4, 6])

In [7]:
# Subtraction -> Performs element wise subtraction [1-3 2-4] = [-2, -2]
a - b

array([-2, -2])

In [8]:
# Multiplication -> Performs element wise subtraction [1*3 2*4] = [3, 8]
a * b 

array([3, 8])

In [9]:
# Division -> Performs element wise division [1/3 2/4] = [0.33 0.5]
a / b

array([0.33333333, 0.5       ])

Often times in linear algebra, vectors operations involve scalars (or constants) as well. When operating a scalar with a vector, we follow broadcasting, i.e. a scalar gets operated on all vector elements.

In [34]:
# [3+1 3+2] = [4 5]
3 + a 

array([4, 5])

In [14]:
# [4-1  4-2] = [3 2]
4 - a

array([3, 2])

In [15]:
# [2*1 2*2] = [2 4]
2 * a

array([2, 4])

In [44]:
# [4/1 4/2] = [4 2]
4 / a

array([4., 2.])

In [46]:
# [1/4 2/4] = [0.25 0.5]
a / 4

array([0.25, 0.5 ])

As vectors are nd-arrays in Python, we can calculate their magnitude as well. Generally, L1 and L2 norms are used for calculating the magnitude of a vector. Here is a <a href="https://www.youtube.com/watch?v=5fN2J8wYnfw">good video</a> to learn more about L1 and L2 norms. 

Since, `a` is a 2D vector with elements `[1, 2]`, $L_1$ and $L_2$ norm are calculated as,

$$

L_1 = \lVert \vec{a} \rVert_{1} = |a_1| + |a_2|  = |1| + |2| = 1 + 2 = 3 \ units \\ \\

$$

$$

L_2 = \lVert \vec{a} \rVert_{2} = \sqrt{a_1^2 + a_2^2} = \sqrt{1^{2} + 2^{2}} = \sqrt{5} = 2.236 \ units \\ \\

$$

And,through generalization, $L_p$ norm or p-norm is calculated as,

$$
\lVert \vec{a} \rVert_p = \left(\sum_{i=1}^{n} |a_i|\ ^p\right)^{\frac{1}{p}}
$$

Here `n` is the number of elements in the vector whereas `p` is the norm. To learn more about $L_p$ norm, refer to this <a href="https://www.youtube.com/watch?v=NKuLYRui-NU" target="__blank__">video</a>.

In [35]:
# L1 Norm
l1_norm = np.sum(np.abs(a))

# L2 norm
l2_norm = np.sqrt(np.square(a[0]) + np.square(a[1]))

print(f"L1 norm of vector a = {l1_norm}")
print(f"L2 norm of vector a = {l2_norm}")

L1 norm of vector a = 3
L2 norm of vector a = 2.23606797749979


There are two p values for which the calculation of $L_p$ norm is not intuitive, 0 and $\infty$. For these the following calculations are done,
$$

\lVert \vec{a} \rVert_0 = \text{Count of all non-zero elements in a} = 2 \ units
$$

$$
\lVert \vec{a} \rVert_\infty = max(|a_i|) = max(|a_1|, |a_2|) = max(|1|, |2|) = 2 \ units
$$

In [43]:
# L1 Norm
lzero_norm = np.count_nonzero(a)

# L2 norm
linfinity_norm = np.max(np.abs(a))

print(f"L0 norm of vector a = {l0_norm}")
print(f"Linfinity norm of vector a = {linfinity_norm}")

L0 norm of vector a = 2.0
Linfinity norm of vector a = 2


Note: $L_0$ is not a vector norm since it doesn't follow the properties dictated to be a norm. The properties are:

- Non-negativity: The norm should always be non-negative.
- Definiteness: The norm is zero if and only if the vector is zero, i.e., zero vector.
- Triangle inequality: The norm of a sum of two vectors is no more than the sum of their norms.
- Homogeneity: Multiplying a vector by a scalar multiplies the norm of the vector by the absolute value of the scalar.